version: 2
formats: 
  - htmlzip
build:
  image: latest
python:
    version: 3.6
    install:
        - requirements: requirements.txt
        - method: setuptools
          path: .
    system_packages: true
submodules:
    include: all
    recursive: true
sphinx:
  builder: html
  configuration: doc/source/conf.py
  fail_on_warning: False