version: 2
formats: all
python:
    version: 3.5
    install:
        - requirements: requirements.txt
        - method: setuptools
          path: .
    system_packages: true
submodules:
    include: all
    recursive: true
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: False