version: 2
formats: all
python:
    version: 3.5
    install:
        - requirements: requirements.txt
        - method: pip
          path: .
    system_packages: true
submodules:
    include: all
    recursive: true