notifications:
  email: false
language: python
os: linux
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
#before_install:
#  - cd Fynance && python setup.py build_ext --inplace
# command to install dependencies
install:
  - pip install -r requirements.txt > /dev/null 2>&1
  - python3 setup.py build_ext --inplace
# command to run tests
script: 
  - pytest