notifications:
  email: false
language: python
os: linux
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
cache:
  directories:
    - $HOME/.cache # cache
#before_install:
#  - cd Fynance && python setup.py build_ext --inplace
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python3 setup.py build_ext --inplace
# command to run tests
script: 
  - pytest