#!/usr/bin/env python3
# coding: utf-8

""" Tests for the maximum-likelihood GARCH-family volatility driver. """

# Third-party packages
import numpy as np
import pytest

# Local packages
from fynance.estimator import VolatilityResult, fit_volatility
from fynance.models.econometric_models import (
    _mean_abs_standardized_t,
    loglik_garch,
)

# --------------------------------------------------------------------------- #
#                              Simulation helpers                             #
# --------------------------------------------------------------------------- #


def _draw(rng, dist, nu, T):
    """ Unit-variance innovation draws matching the kernel conventions. """
    if dist == 'normal':
        return rng.standard_normal(T)

    return rng.standard_t(nu, T) * np.sqrt((nu - 2.0) / nu)


def _simulate(model, dist, params, T, seed):
    """ Simulate a return path from the kernels' own recursion conventions. """
    rng = np.random.default_rng(seed)
    nu = params.get('nu', 8.0)
    z = _draw(rng, dist, nu, T)
    omega, alpha, beta = params['omega'], params['alpha'], params['beta']
    gamma = params.get('gamma', 0.0)
    y = np.empty(T)

    if model in ('garch', 'gjr'):
        var = omega  # sigma_0^2 = omega.
        y[0] = np.sqrt(var) * z[0]
        for t in range(1, T):
            ind = 1.0 if y[t - 1] < 0.0 else 0.0
            var = omega + (alpha + gamma * ind) * y[t - 1] ** 2 + beta * var
            y[t] = np.sqrt(var) * z[t]

    else:  # egarch.
        maz = _mean_abs_standardized_t(nu) if dist == 't' else np.sqrt(2 / np.pi)
        log_var = omega
        y[0] = np.exp(0.5 * log_var) * z[0]
        for t in range(1, T):
            log_var = (omega + beta * log_var
                       + alpha * (abs(z[t - 1]) - maz) + gamma * z[t - 1])
            y[t] = np.exp(0.5 * log_var) * z[t]

    return y


# (model, dist, true params, seed) — seeds chosen for robust <15% recovery.
RECOVERY_CASES = [
    ('garch', 'normal', dict(omega=0.05, alpha=0.10, beta=0.85), 2),
    ('garch', 't', dict(omega=0.05, alpha=0.10, beta=0.85, nu=6.0), 2),
    ('gjr', 'normal', dict(omega=0.05, alpha=0.06, gamma=0.12, beta=0.86), 4),
    ('gjr', 't',
     dict(omega=0.05, alpha=0.06, gamma=0.12, beta=0.86, nu=6.0), 3),
    ('egarch', 'normal',
     dict(omega=-0.1, alpha=0.15, gamma=-0.10, beta=0.95), 0),
    ('egarch', 't',
     dict(omega=-0.1, alpha=0.15, gamma=-0.10, beta=0.95, nu=6.0), 3),
]


# --------------------------------------------------------------------------- #
#                            Parameter recovery                               #
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize('model,dist,true,seed', RECOVERY_CASES)
def test_parameter_recovery(model, dist, true, seed):
    # On a long simulated series the MLE recovers every parameter within 15%.
    y = _simulate(model, dist, true, T=5000, seed=seed)
    res = fit_volatility(y, model=model, dist=dist)

    assert isinstance(res, VolatilityResult)
    assert res.model == model and res.dist == dist and res.n_obs == 5000
    assert set(res.params) == set(true)

    for name, truth in true.items():
        rel = abs(res.params[name] - truth) / abs(truth)
        assert rel <= 0.15, f"{model}-{dist} {name}: {res.params[name]} vs {truth}"


@pytest.mark.parametrize('model,dist,true,seed', RECOVERY_CASES)
def test_loglik_fit_at_least_truth(model, dist, true, seed):
    # The maximised log-likelihood is never below the truth's log-likelihood.
    y = _simulate(model, dist, true, T=5000, seed=seed)
    res = fit_volatility(y, model=model, dist=dist)

    names = ['omega', 'alpha', 'beta'] if model == 'garch' else \
        ['omega', 'alpha', 'gamma', 'beta']
    if dist == 't':
        names = names + ['nu']
    truth_vec = np.array([true[n] for n in names])
    ll_truth = loglik_garch(truth_vec, y - np.mean(y), model=model, dist=dist)

    assert res.loglik >= ll_truth - 1e-6


# --------------------------------------------------------------------------- #
#                           Information criteria                              #
# --------------------------------------------------------------------------- #


def test_aic_bic_formulas_exact():
    y = _simulate('garch', 'normal', dict(omega=0.05, alpha=0.10, beta=0.85),
                  T=2000, seed=1)
    res = fit_volatility(y, model='garch', dist='normal')
    k, n = len(res.params), res.n_obs

    assert np.isclose(res.aic, 2 * k - 2 * res.loglik)
    assert np.isclose(res.bic, k * np.log(n) - 2 * res.loglik)


def test_aic_ranking_prefers_true_family():
    # Data generated by GJR-t: among the six model x dist fits, GJR-t wins AIC.
    true = dict(omega=0.05, alpha=0.06, gamma=0.12, beta=0.86, nu=6.0)
    y = _simulate('gjr', 't', true, T=5000, seed=3)

    aic = {}
    for model in ('garch', 'gjr', 'egarch'):
        for dist in ('normal', 't'):
            aic[(model, dist)] = fit_volatility(y, model=model, dist=dist).aic

    assert min(aic, key=aic.get) == ('gjr', 't')


# --------------------------------------------------------------------------- #
#                                 Forecast                                    #
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize('model', ['garch', 'gjr'])
def test_forecast_h1_equals_filter_next_step(model):
    # The one-step variance forecast is exactly the filter's next-step value.
    true = dict(omega=0.05, alpha=0.06, gamma=0.10, beta=0.86)
    y = _simulate(model, 'normal', true, T=3000, seed=0)
    res = fit_volatility(y, model=model, dist='normal')

    omega, alpha = res.params['omega'], res.params['alpha']
    beta = res.params['beta']
    gamma = res.params.get('gamma', 0.0)
    eps_last = res.std_residuals[-1] * res.conditional_vol[-1]
    ind = 1.0 if eps_last < 0.0 else 0.0
    expected = (omega + (alpha + gamma * ind) * eps_last ** 2
                + beta * res.conditional_vol[-1] ** 2)

    assert res.forecast(1)[0] == expected


@pytest.mark.parametrize('model', ['garch', 'gjr'])
def test_forecast_converges_to_unconditional_variance(model):
    true = dict(omega=0.05, alpha=0.06, gamma=0.10, beta=0.86)
    y = _simulate(model, 'normal', true, T=3000, seed=0)
    res = fit_volatility(y, model=model, dist='normal')

    omega, alpha = res.params['omega'], res.params['alpha']
    beta = res.params['beta']
    gamma = res.params.get('gamma', 0.0)
    uncond = omega / (1.0 - alpha - beta - 0.5 * gamma)

    fc = res.forecast(500)
    assert fc.shape == (500,)
    assert np.all(fc > 0.0)
    assert abs(fc[-1] - uncond) / uncond < 0.10


def test_egarch_forecast_is_positive_and_seeded():
    true = dict(omega=-0.1, alpha=0.15, gamma=-0.10, beta=0.95)
    y = _simulate('egarch', 'normal', true, T=3000, seed=0)
    res = fit_volatility(y, model='egarch', dist='normal')

    fc = res.forecast(10, n_sims=2000, seed=0)
    assert fc.shape == (10,)
    assert np.all(fc > 0.0)
    # Monte-Carlo is seeded: identical seed reproduces the path exactly.
    assert np.array_equal(fc, res.forecast(10, n_sims=2000, seed=0))


def test_forecast_bad_horizon_raises():
    y = _simulate('garch', 'normal', dict(omega=0.05, alpha=0.1, beta=0.85),
                  T=500, seed=0)
    res = fit_volatility(y, model='garch', dist='normal')
    with pytest.raises(ValueError, match='h must be'):
        res.forecast(0)


# --------------------------------------------------------------------------- #
#                                 Simulate                                    #
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize('model', ['garch', 'gjr'])
def test_simulate_unconditional_vol(model):
    true = dict(omega=0.05, alpha=0.06, gamma=0.10, beta=0.86)
    y = _simulate(model, 'normal', true, T=3000, seed=0)
    res = fit_volatility(y, model=model, dist='normal')

    omega, alpha = res.params['omega'], res.params['alpha']
    beta = res.params['beta']
    gamma = res.params.get('gamma', 0.0)
    uncond_std = np.sqrt(omega / (1.0 - alpha - beta - 0.5 * gamma))

    sim = res.simulate(30000, seed=0)
    assert sim.shape == (30000,)
    assert np.all(np.isfinite(sim))
    assert abs(np.std(sim) - uncond_std) / uncond_std < 0.10


def test_simulate_is_seeded():
    y = _simulate('egarch', 'normal',
                  dict(omega=-0.1, alpha=0.15, gamma=-0.10, beta=0.95),
                  T=1000, seed=0)
    res = fit_volatility(y, model='egarch', dist='normal')
    a = res.simulate(500, seed=42)
    b = res.simulate(500, seed=42)
    c = res.simulate(500, seed=7)

    assert np.array_equal(a, b)
    assert not np.array_equal(a, c)


# --------------------------------------------------------------------------- #
#                              Standard errors                                #
# --------------------------------------------------------------------------- #


def test_std_errors_finite_and_positive_on_well_behaved_fit():
    y = _simulate('garch', 'normal', dict(omega=0.05, alpha=0.10, beta=0.85),
                  T=5000, seed=2)
    res = fit_volatility(y, model='garch', dist='normal')

    assert set(res.std_errors) == set(res.params)
    for name, se in res.std_errors.items():
        assert np.isfinite(se) and se > 0.0, name


# --------------------------------------------------------------------------- #
#                          Options and validation                            #
# --------------------------------------------------------------------------- #


def test_x0_override_is_used():
    # An explicit x0 must be accepted and still yield a valid fit.
    y = _simulate('garch', 'normal', dict(omega=0.05, alpha=0.10, beta=0.85),
                  T=2000, seed=0)
    res = fit_volatility(y, model='garch', dist='normal',
                         x0=[0.1, 0.05, 0.9])
    assert np.isfinite(res.loglik)
    assert set(res.params) == {'omega', 'alpha', 'beta'}


def test_conditional_vol_and_residuals_consistent():
    y = _simulate('garch', 'normal', dict(omega=0.05, alpha=0.10, beta=0.85),
                  T=1000, seed=0)
    res = fit_volatility(y, model='garch', dist='normal')

    assert res.conditional_vol.shape == (1000,)
    assert res.std_residuals.shape == (1000,)
    assert np.all(res.conditional_vol > 0.0)
    # std_residuals == (demeaned y) / conditional_vol.
    yd = y - np.mean(y)
    assert np.allclose(res.std_residuals, yd / res.conditional_vol)


@pytest.mark.parametrize('bad', [
    dict(model='arch'),
    dict(dist='cauchy'),
])
def test_bad_model_or_dist_raises(bad):
    y = np.random.default_rng(0).standard_normal(300)
    with pytest.raises(ValueError):
        fit_volatility(y, **bad)
